In [10]:
import matplotlib.pyplot as plt
import pandas as pd 
ps1=pd.read_csv("PS1.txt",sep="\t",header=None)
ps2=pd.read_csv("PS2.txt",sep="\t",header=None)
ps2_p=pd.read_csv("profile.txt",sep="\t",header=None)
ps2_p.columns = [
    "cooler",
    "valve",
    "pump_leakage",
    "accumulator",
    "stability"
]

pscandtable=pd.DataFrame()

ps2_00_10=ps2.iloc[:,0000:1001]
ps201_features=pd.DataFrame()
ps201_features["mean"]=ps2_00_10.mean(axis=1)
ps201_features["std"]=ps2_00_10.std(axis=1)
ps201_features["min"]=ps2_00_10.min(axis=1)
ps201_features["max"]=ps2_00_10.max(axis=1)
ps201_features["range"]=-(ps201_features["min"]-ps201_features["max"])

ps2_20_50=ps2.iloc[:,2000:5001]
ps2_features=pd.DataFrame()
ps2_features["mean"]=ps2_20_50.mean(axis=1)
ps2_features["std"]=ps2_20_50.std(axis=1)
ps2_features["min"]=ps2_20_50.min(axis=1)
ps2_features["max"]=ps2_20_50.max(axis=1)
ps2_features["range"]=-(ps2_features["min"]-ps2_features["max"])
ps2_features = pd.concat([ps2_features, ps2_p],axis=1)

ps1_20_50=ps1.iloc[:,2000:5001]
ps1_features=pd.DataFrame()
ps1_features["mean"]=ps1_20_50.mean(axis=1)
ps1_features["std"]=ps1_20_50.std(axis=1)
ps1_features["min"]=ps1_20_50.min(axis=1)
ps1_features["max"]=ps1_20_50.max(axis=1)
ps1_features["range"]=-(ps1_features["min"]-ps1_features["max"])


pscandtable = pd.concat([ps201_features["std"],
ps201_features["range"],ps201_features["mean"],ps2_features["std"],ps2_features["range"],ps2_features["mean"],ps1_features["std"],
ps1_features["range"],ps1_features["mean"],ps2_p],axis=1)
pscandtable.columns = [
    "PS2_0_10_std",
    "PS2_0_10_range",
    "PS2_0_10_mean",
    "PS2_20_50_std",
    "PS2_20_50_range",
    "PS2_20_50_mean",
    "PS1_20_50_std",
    "PS1_20_50_range",
    "PS1_20_50_mean",
    "cooler",
    "valve",
    "pump_leakage",
    "accumulator",
    "stability"]

pscandtable 


,PS2_0_10_std,PS2_0_10_range,PS2_0_10_mean,PS2_20_50_std,PS2_20_50_range,PS2_20_50_mean,PS1_20_50_std,PS1_20_50_range,PS1_20_50_mean,cooler,valve,pump_leakage,accumulator,stability
0,33.480175,156.99,9.626265,4.899670,15.88,133.639157,4.846070,15.51,159.491803,3,100,0,130,1
1,33.509307,157.56,9.680272,4.911799,16.09,133.478421,4.833130,15.75,159.270586,3,100,0,130,1
2,33.361667,156.97,9.572975,4.953553,16.03,133.264485,4.884964,15.59,158.991403,3,100,0,130,1
3,33.305797,156.44,9.513450,4.974764,16.25,133.167907,4.892623,15.56,158.820500,3,100,0,130,1
4,33.317389,158.13,9.609307,4.978708,16.50,132.978157,4.899436,15.83,158.601156,3,100,0,130,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2200,34.477626,167.49,9.824872,4.753403,15.20,133.790093,4.671487,14.85,159.724155,100,100,0,90,0
2201,34.601202,167.27,9.885318,4.767095,15.41,133.796611,4.680823,14.85,159.699873,100,100,0,90,0
2202,34.371979,167.34,9.792434,4.753229,15.38,133.769783,4.681189,14.97,159.694032,100,100,0,90,0
2203,34.550266,167.52,9.886776,4.740283,15.30,133.792493,4.664957,14.91,159.705591,100,100,0,90,0


In [11]:
pscandtable.head()

,PS2_0_10_std,PS2_0_10_range,PS2_0_10_mean,PS2_20_50_std,PS2_20_50_range,PS2_20_50_mean,PS1_20_50_std,PS1_20_50_range,PS1_20_50_mean,cooler,valve,pump_leakage,accumulator,stability
0,33.480175,156.99,9.626265,4.899670,15.88,133.639157,4.846070,15.51,159.491803,3,100,0,130,1
1,33.509307,157.56,9.680272,4.911799,16.09,133.478421,4.833130,15.75,159.270586,3,100,0,130,1
2,33.361667,156.97,9.572975,4.953553,16.03,133.264485,4.884964,15.59,158.991403,3,100,0,130,1
3,33.305797,156.44,9.513450,4.974764,16.25,133.167907,4.892623,15.56,158.820500,3,100,0,130,1
4,33.317389,158.13,9.609307,4.978708,16.50,132.978157,4.899436,15.83,158.601156,3,100,0,130,1


In [12]:
pscandtable.shape


(2205, 14)

In [13]:
print("Shape:", pscandtable.shape)

print("\nData types:")
print(pscandtable.dtypes)

print("\nMissing values:")
print(pscandtable.isna().sum())

print("\nNumber of unique values:")
print(pscandtable.nunique())

print("\nDuplicate column names:")
print(pscandtable.columns[pscandtable.columns.duplicated()])

Shape: (2205, 14)

Data types:
PS2_0_10_std       float64
PS2_0_10_range     float64
PS2_0_10_mean      float64
PS2_20_50_std      float64
PS2_20_50_range    float64
PS2_20_50_mean     float64
PS1_20_50_std      float64
PS1_20_50_range    float64
PS1_20_50_mean     float64
cooler               int64
valve                int64
pump_leakage         int64
accumulator          int64
stability            int64
dtype: object

Missing values:
PS2_0_10_std       0
PS2_0_10_range     0
PS2_0_10_mean      0
PS2_20_50_std      0
PS2_20_50_range    0
PS2_20_50_mean     0
PS1_20_50_std      0
PS1_20_50_range    0
PS1_20_50_mean     0
cooler             0
valve              0
pump_leakage       0
accumulator        0
stability          0
dtype: int64

Number of unique values:
PS2_0_10_std       2205
PS2_0_10_range      273
PS2_0_10_mean      2205
PS2_20_50_std      2205
PS2_20_50_range     661
PS2_20_50_mean     2205
PS1_20_50_std      2205
PS1_20_50_range     534
PS1_20_50_mean     2205
cooler     

In [14]:
feature_cols = [
    "PS2_0_10_std",
    "PS2_0_10_range",
    "PS2_0_10_mean",
    "PS2_20_50_std",
    "PS2_20_50_range",
    "PS2_20_50_mean",
    "PS1_20_50_std",
    "PS1_20_50_range",
    "PS1_20_50_mean"
]

X_candidates = pscandtable[feature_cols]
corr = X_candidates.corr()
print(corr)

                 PS2_0_10_std  PS2_0_10_range  PS2_0_10_mean  PS2_20_50_std  \
PS2_0_10_std         1.000000        0.247692       0.992109      -0.149364   
PS2_0_10_range       0.247692        1.000000       0.182334      -0.217175   
PS2_0_10_mean        0.992109        0.182334       1.000000      -0.119987   
PS2_20_50_std       -0.149364       -0.217175      -0.119987       1.000000   
PS2_20_50_range     -0.245768       -0.368664      -0.196777       0.674392   
PS2_20_50_mean      -0.228799       -0.282946      -0.193575       0.504688   
PS1_20_50_std       -0.114228       -0.169385      -0.090846       0.987399   
PS1_20_50_range     -0.245165       -0.370653      -0.195599       0.674972   
PS1_20_50_mean      -0.220866       -0.265403      -0.188009       0.500259   

                 PS2_20_50_range  PS2_20_50_mean  PS1_20_50_std  \
PS2_0_10_std           -0.245768       -0.228799      -0.114228   
PS2_0_10_range         -0.368664       -0.282946      -0.169385   
PS2_0_10

In [15]:

X = pscandtable[feature_cols]
y = pscandtable["pump_leakage"]
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)


In [16]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(1764, 9)
(441, 9)
(1764,)
(441,)


In [17]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

model = Pipeline([
    ("scaler", StandardScaler()),
    ("classifier", LogisticRegression())
])
model.fit(X_train, y_train)

,"steps steps: list of tuplesList of (name of step, estimator) tuples that are to be chained insequential order. To be compatible with the scikit-learn API, all stepsmust define `fit`. All non-last steps must also define `transform`. See:ref:`Combining Estimators <combining_estimators>` for more details.","[('scaler', ...), ('classifier', ...)]"
,"transform_input transform_input: list of str, default=NoneThe names of the :term:`metadata` parameters that should be transformed by thepipeline before passing it to the step consuming it.This enables transforming some input arguments to ``fit`` (other than ``X``)to be transformed by the steps of the pipeline up to the step which requiresthem. Requirement is defined via :ref:`metadata routing <metadata_routing>`.For instance, this can be used to pass a validation set through the pipeline.You can only set this if metadata routing is enabled, which youcan enable using ``sklearn.set_config(enable_metadata_routing=True)``... versionadded:: 1.6",None
,"memory memory: str or object with the joblib.Memory interface, default=NoneUsed to cache the fitted transformers of the pipeline. The last stepwill never be cached, even if it is a transformer. By default, nocaching is performed. If a string is given, it is the path to thecaching directory. Enabling caching triggers a clone of the transformersbefore fitting. Therefore, the transformer instance given to thepipeline cannot be inspected directly. Use the attribute ``named_steps``or ``steps`` to inspect estimators within the pipeline. Caching thetransformers is advantageous when fitting is time consuming. See:ref:`sphx_glr_auto_examples_neighbors_plot_caching_nearest_neighbors.py`for an example on how to enable caching.",None
,"verbose verbose: bool, default=FalseIf True, the time elapsed while fitting each step will be printed as itis completed.",False
Name,Type,Value
"classes_ classes_: ndarray of shape (n_classes,)The classes labels. Only exist if the last step of the pipeline is aclassifier.","ndarray[int64](3,)","[0,1,2]"
"feature_names_in_ feature_names_in_: ndarray of shape (`n_features_in_`,)Names of features seen during :term:`fit`. Only defined if theunderlying estimator exposes such an attribute when fit... versionadded:: 1.0","ndarray[object](9,)","['PS2_0_10_std','PS2_0_10_range','PS2_0_10_mean',...,'PS1_20_50_std', 'PS1_20_50_range','PS1_20_50_mean']"
n_features_in_ n_features_in_: intNumber of features seen during :term:`fit`. Only defined if theunderlying first estimator in `steps` exposes such an attributewhen fit... versionadded:: 0.24,int,9
,"copy copy: bool, default=TrueIf False, try to avoid a copy and do inplace scaling instead.This is not guaranteed to always work inplace; e.g. if the data isnot a NumPy array or scipy.sparse CSR matrix, a copy may still bereturned.",True
,"with_mean with_mean: bool, default=TrueIf True, center the data before scaling.This does not work (and will raise an exception) when attempted onsparse matrices, because centering them entails building a densematrix which in common use cases is likely to be too large to fit inmemory.",True
,"with_std with_std: bool, default=TrueIf True, scale the data to unit variance (or equivalently,unit standard deviation).",True


In [18]:
print(model)

Pipeline(steps=[('scaler', StandardScaler()),
                ('classifier', LogisticRegression())])


In [19]:
print(model.classes_)

[0 1 2]


In [20]:
y_pred = model.predict(X_test)

print(y_pred[:20])

[0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 2 0 1 2 0]


In [21]:
print("\nActual:")
print(y_test.iloc[:20].to_numpy())


Actual:
[0 2 0 2 1 0 0 0 0 0 0 0 0 0 0 2 0 0 1 1]


In [22]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)

print(cm)

[[223  18   3]
 [ 60  20  19]
 [ 60  19  19]]


In [24]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.65      0.91      0.76       244
           1       0.35      0.20      0.26        99
           2       0.46      0.19      0.27        98

    accuracy                           0.59       441
   macro avg       0.49      0.44      0.43       441
weighted avg       0.54      0.59      0.54       441

